### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by debxylen** [umangshrestha/nmi#1]
im still confused:
how do i add stuff? 
like i want to make if a user writes "cmdargs[0]" it will be the value of the passed arguments from command line

**Comment by umangshrestha** [comment]
Hi,

I didn't understand the query.

Do you want to add the feature for the language to read data from the command line?

My knowledge is limited at the moment and I still need to work on the interpreter project to add features.

I am thinking of adding a keyword that would return the command line arguments. I will get back to you regarding this?

**Comment by debxylen** [comment]
sure
